# Generated by Django 4.2 on 2026-06-15 07:47

import analysis.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('single', 'Single variant'), ('batch', 'Batch (VCF)')], max_length=10)),
                ('assembly', models.CharField(choices=[('GRCh37', 'GRCh37 (hg19)'), ('GRCh38', 'GRCh38 (hg38)')], default='GRCh38', max_length=10)),
                ('input_text', models.CharField(blank=True, max_length=255)),
                ('input_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='results/')),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=analysis.models.default_expiry)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CriterionEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.CharField(max_length=8)),
                ('strength', models.CharField(max_length=16)),
                ('triggered', models.BooleanField(default=True)),
                ('evidence', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceDataVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('mtime', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VariantResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.CharField(max_length=255)),
                ('gene_symbol', models.CharField(blank=True, max_length=64)),
                ('transcript_id', models.CharField(blank=True, max_length=64)),
                ('hgvs_c', models.CharField(blank=True, max_length=128)),
                ('hgvs_p', models.CharField(blank=True, max_length=128)),
                ('classification', models.CharField(blank=True, max_length=64)),
                ('bayesian_score', models.IntegerField(default=0)),
                ('result_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VariantResultCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly', models.CharField(choices=[('GRCh37', 'GRCh37 (hg19)'), ('GRCh38', 'GRCh38 (hg38)')], max_length=10)),
                ('chrom', models.CharField(max_length=16)),
                ('pos', models.BigIntegerField()),
                ('ref', models.CharField(max_length=512)),
                ('alt', models.CharField(max_length=512)),
                ('engine_version', models.CharField(max_length=64)),
                ('refdata_signature', models.CharField(max_length=64)),
                ('result_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='variantresultcache',
            index=models.Index(fields=['assembly', 'chrom', 'pos', 'ref', 'alt'], name='analysis_va_assembl_6b32ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='variantresultcache',
            unique_together={('assembly', 'chrom', 'pos', 'ref', 'alt', 'engine_version', 'refdata_signature')},
        ),
        migrations.AddField(
            model_name='variantresult',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analysis.analysisjob'),
        ),
        migrations.AddField(
            model_name='criterionedit',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criterion_edits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='criterionedit',
            name='variant_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='analysis.variantresult'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
